version: "3"

networks:
  django:
    name: django

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - django
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - django
    environment:
      - ENV=server
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - db
    depends_on:
      - db