# Generated by Django 4.1.3 on 2022-12-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_authors_slug_alter_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.authors'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.categories'),
        ),
    ]
