# Generated by Django 4.1.3 on 2023-01-02 15:08

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_author_id_articles_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
